import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTranslationAlterConferencePublication1706292498583 implements MigrationInterface {
  name = 'CreateTranslationAlterConferencePublication1706292498583';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "translation" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying, "language" character varying, "year" integer, "publicationCountry" character varying, "issn" character varying, "originalTitle" character varying, "originalLanguage" character varying, "originalAuthor" character varying, "originalPublicationCity" character varying, "bigArea" character varying, "area" character varying, "subArea" character varying, "speciality" character varying, "authors" character varying(1500), "professor_id" integer, CONSTRAINT "PK_7aef875e43ab80d34a0cdd39c70" PRIMARY KEY ("id"))`,
    );

    await queryRunner.query(`ALTER TABLE "conference_publication" ADD "nature" character varying(50)`);

    await queryRunner.query(
      `ALTER TABLE "translation" ADD CONSTRAINT "FK_a04268b75b54492e3a4504231a3" FOREIGN KEY ("professor_id") REFERENCES "professor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "translation" DROP CONSTRAINT "FK_a04268b75b54492e3a4504231a3"`);

    await queryRunner.query(`ALTER TABLE "conference_publication" DROP COLUMN "nature"`);

    await queryRunner.query(`DROP TABLE "translation"`);
  }
}
